export var countries: string[] = ['Albania', 'Algeria',
    'Andorra', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bangladesh', 'Belarus',
    'Belgium', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil',
    'Bulgaria', 'Canada',
    'China', 'Colombia', 'Costa Rica',
    'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Ecuador',
    'Egypt', 'Estonia',
    'Finland', 'France', 'Georgia', 'Germany', 'Greece',
    'Iceland', 'India', 'Indonesia', 'Ireland', 'Israel',
    'Italy', 'Jamaica', 'Japan', 'Latvia',
    'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Malta', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
    'Netherlands', 'New Zealand', 'Norway', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
    'Romania', 'Russia',
    'Serbia', 'Singapore',
    'Slovakia', 'Slovenia', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Ukraine',
    'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan',
    'Vietnam', 'Venezuela',
]